name: Security+ 501 (SY0-501) Boot Camp
markdown: kramdown
kramdown:
  hard_wrap: false
  input: GFM
  syntax_highlighter: rouge
mathjax: true
baseurl: /SecPlus501-2019
exclude: [morea]
morea_theme: superhero
morea_navbar_items:
  #- Prerequisites
  - Modules
  - Outcomes
  - Readings
  - Experiences
  - Assessments
  #- Schedule

# The following properties are optional.
# See the User Guide (http://morea-framework.github.io/userguide.html) for more info.

# morea_course: ics311
# morea_domain: http://morea-framework.github.io/
# morea_google_analytics_tracking_id: "<your tracking id here>"

#morea_head_breadcrumb_link: "https://pcatt.org"
#morea_head_breadcrumb_label: "PCATT Site"